common: &common
 adapter: postgresql
 username: user_name
 password: user_password
 encoding: utf8
 pool: 5

development:
  <<: *common
  database: tutoriapps_development

test:
  <<: *common
  database: tutoriapps_test

production:
 <<: *common
 database: tutoriapps_production